sudo: required
language: c
os:
  - linux
  - osx
services: docker
osx_image: xcode7.3
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y aspcud; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install opam; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 60 ./build-infer.sh --yes java --user-opam-switch --only-setup-opam; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval `opam env`; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then opam install --yes infer .; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./.travis/local_install_tests.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis/docker_tests.sh; fi
  - git diff --exit-code
